// Single source of truth for the whole landing page. Edit this file and the
// hero, code samples, feature grid, benchmarks, logo wall and footer all update.

export const project = {
  name: 'Drift',
  // The npm binary name people actually type.
  bin: 'drift',
  tagline: 'Database migrations that never drift.',
  blurb:
    'Drift diffs your schema against your live database, then writes the migration for you — type-safe, reviewable SQL you can read before it runs. No more hand-edited up/down files, no more “works on my machine” drift between environments.',
  install: 'npm i -D drift-cli',
  ecosystem: 'Node · TypeScript',
  // Believable social proof.
  stars: '14.2k',
  starsExact: '14,218',
  version: 'v2.4.0',
  license: 'MIT',
  repo: 'https://github.com/driftlabs/drift',
  discord: 'https://discord.gg/drift',
  docs: 'https://driftcli.dev/docs',
  npm: 'https://www.npmjs.com/package/drift-cli',
};

export const databases = ['PostgreSQL', 'MySQL', 'SQLite', 'PlanetScale', 'Neon', 'Turso'];

// The hero code block — a real, copy-able first command.
export const quickStart = {
  intro: 'Point Drift at your database and let it write the first migration:',
  lang: 'bash',
  code: `# install
npm i -D drift-cli

# scaffold drift.config.ts + connect your database
npx drift init

# diff your schema against the database and generate SQL
npx drift generate add_orders_table

# preview, then apply — every migration is plain reviewable SQL
npx drift status
npx drift push`,
};

// The "core workflow" sample — a schema in code, then the generated migration.
export const schemaSample = {
  title: 'You write the schema you want…',
  lang: 'typescript',
  code: `// schema.ts — describe the shape, not the diff
import { table, text, uuid, timestamp, int } from 'drift-cli';

export const orders = table('orders', {
  id:        uuid('id').primaryKey().default('gen_random_uuid()'),
  email:     text('email').notNull(),
  total:     int('total_cents').notNull(),
  status:    text('status').notNull().default('pending'),
  createdAt: timestamp('created_at').notNull().default('now()'),
});`,
};

export const migrationSample = {
  title: '…Drift writes the migration.',
  lang: 'sql',
  code: `-- migrations/0007_add_orders_table.sql  (generated by drift)
-- ↑ 1 table added · 0 columns dropped · safe to run

CREATE TABLE "orders" (
  "id"         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email"      text NOT NULL,
  "total_cents" integer NOT NULL,
  "status"     text NOT NULL DEFAULT 'pending',
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "orders_email_idx" ON "orders" ("email");`,
};

export const features = [
  {
    icon: 'bolt',
    title: 'Fast',
    body: 'A Rust diff engine reads your schema and introspects the database in one pass. Generating a migration on a 200-table schema takes under 40ms — fast enough to run on every save.',
  },
  {
    icon: 'shield',
    title: 'Type-safe',
    body: 'Your schema is TypeScript, so column names, types and relations are checked at compile time. Rename a column and every query that referenced it lights up red in your editor.',
  },
  {
    icon: 'spark',
    title: 'Zero-config',
    body: 'Run drift init and it detects your database from DATABASE_URL, picks the right dialect, and writes a one-file config. No adapters to wire up, no plugins to install.',
  },
  {
    icon: 'plug',
    title: 'Framework-agnostic',
    body: 'Drift only owns your migrations — keep using Prisma, Drizzle, Kysely or raw SQL for queries. Postgres, MySQL, SQLite, and serverless drivers all speak the same commands.',
  },
  {
    icon: 'eye',
    title: 'Reviewable SQL',
    body: 'Every migration is a plain .sql file you commit to git. Read it, edit it, comment on it in a PR. Nothing is hidden behind a binary format or an opaque migration table.',
  },
  {
    icon: 'undo',
    title: 'Safe rollbacks',
    body: 'Each migration ships with a generated down step and a destructive-change guard. drift push --dry-run prints the exact plan; drift rollback reverts the last batch cleanly.',
  },
];

export const steps = [
  {
    n: '01',
    cmd: 'drift init',
    title: 'Connect',
    body: 'Drift reads DATABASE_URL, detects your dialect, and writes drift.config.ts plus an empty migrations folder. One command, no questions.',
  },
  {
    n: '02',
    cmd: 'drift generate',
    title: 'Diff & generate',
    body: 'Change your schema, then run generate. Drift compares the desired shape to the live database and emits a numbered, reviewable SQL migration with up and down steps.',
  },
  {
    n: '03',
    cmd: 'drift push',
    title: 'Apply anywhere',
    body: 'Run push in CI, on a teammate’s laptop, or against prod. Drift applies only the migrations that haven’t run yet and records them — every environment ends up identical.',
  },
];

export const benchmark = {
  heading: 'Built for the inner loop',
  sub: 'Time to generate and apply a migration on a 50-table Postgres schema. Lower is better — measured on an M2 Air, median of 20 runs.',
  rows: [
    { label: 'Drift', value: 38, display: '38 ms', us: true },
    { label: 'Hand-written + manual diff', value: 100, display: '~6 min', us: false, caveat: 'human-paced' },
    { label: 'ORM migrate (Node)', value: 71, display: '210 ms', us: false },
    { label: 'ORM migrate (Python)', value: 86, display: '640 ms', us: false },
  ],
  note: 'The bars compare tool overhead. The real win is the “~6 min” row: Drift removes the hand-written diff entirely.',
};

export const usedBy = [
  { name: 'Northwind', tag: 'logistics' },
  { name: 'Lumen', tag: 'fintech' },
  { name: 'Tideline', tag: 'maps API' },
  { name: 'Offcuts', tag: 'commerce' },
  { name: 'Brightside', tag: 'analytics' },
  { name: 'Copperline', tag: 'devtools' },
  { name: 'Plateful', tag: 'health' },
  { name: 'Quarterup', tag: 'gaming' },
];

export const testimonial = {
  quote:
    'We deleted 1,400 lines of hand-rolled migration scripts the week we adopted Drift. Generated SQL we can actually read in review, and prod and staging finally stopped drifting apart.',
  author: 'Priya Raman',
  role: 'Staff Engineer, Northwind',
};

export const docCards = [
  {
    title: 'Quickstart',
    body: 'Go from npm install to your first applied migration in five minutes.',
    href: 'https://driftcli.dev/docs/quickstart',
    kicker: 'Guide',
  },
  {
    title: 'Schema reference',
    body: 'Every column type, constraint and relation helper, with copy-able examples.',
    href: 'https://driftcli.dev/docs/schema',
    kicker: 'Reference',
  },
  {
    title: 'CI recipes',
    body: 'Drop-in GitHub Actions and a drift check gate that fails on unreviewed drift.',
    href: 'https://driftcli.dev/docs/ci',
    kicker: 'Recipe',
  },
  {
    title: 'Migrating in',
    body: 'Adopt Drift on top of an existing Prisma, Drizzle or Rails schema, no rewrite.',
    href: 'https://driftcli.dev/docs/adopt',
    kicker: 'Guide',
  },
];
