#!/usr/bin/env bun
//
// The build. Run it before `sf build` — it produces both halves of the publish.
//
//   1. Pull posts from WordPress.
//   2. Write shared/search-index.ts, which the capsule compiles in so
//      GET /api/search can answer without a database or a call to WordPress.
//   3. Run `sf build` once, to materialize the generated Zero app shell.
//   4. Read the platform import map out of that shell and render home.html and
//      posts/*.html around it, so every article page can mount the island.
//
// Step 3 looks odd and is deliberate: the app shell is the only place the
// content-addressed platform module paths exist, and a static page that wants
// /client.js needs the same map. Running the compile first is cheaper than
// guessing. The real `sf build` afterwards picks up the pages this wrote and
// publishes them beside the capsule.

import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { SITE_NAME, WORDPRESS_URL } from "./config";
import { articleUrl, renderArticle, renderIndex } from "./render";
import { fetchArticles, type Article } from "./wordpress";

const root = path.resolve(import.meta.dirname, "..");
const shellPath = path.join(root, ".spacefast/zero/public/index.html");

function searchDocuments(articles: Article[]) {
  return articles.map((article) => ({
    slug: article.slug,
    title: article.title,
    excerpt: article.excerpt,
    url: articleUrl(article),
    date: article.date.toISOString(),
    categories: [...article.categories, ...article.tags],
    // The haystack: lowercased once here so the server never lowercases at
    // request time. Capped so one very long post cannot dominate the bundle.
    text: `${article.title} ${article.excerpt} ${article.plainText}`.toLowerCase().slice(0, 12_000),
  }));
}

/** The capsule's copy of the index — a module, so it ships inside the server bundle. */
async function writeSearchIndex(documents: ReturnType<typeof searchDocuments>, source: string) {
  const contents = `// GENERATED by \`bun run build\`. Do not edit.
//
// The build-time search index: what GET /api/search searches. Regenerating it is
// how search learns about new WordPress posts — there is no live call back to
// WordPress at request time, by design.

import type { SearchDocument } from "./search";

export const SEARCH_INDEX_SOURCE = ${JSON.stringify(source)};
export const SEARCH_INDEX_BUILT_AT = ${JSON.stringify(new Date().toISOString())};
export const SEARCH_INDEX: SearchDocument[] = ${JSON.stringify(documents, null, 2)};
`;
  await writeFile(path.join(root, "shared/search-index.ts"), contents);
}

/**
 * The `<script type="importmap">…</script>` line from the generated app shell.
 * Without it a static page's `/client.js` cannot resolve `preact` or
 * `@spacefast/zero/client`, and the island silently never mounts.
 */
async function readImportMap(): Promise<string> {
  const shell = await readFile(shellPath, "utf8").catch(() => null);
  const map = shell?.match(/<script type="importmap">[\s\S]*?<\/script>/)?.[0];
  if (!map) {
    throw new Error(
      `No import map in ${shellPath}. The \`sf build\` step above should have written it — ` +
        `run \`sf build\` by hand to see what it says.`,
    );
  }
  return map;
}

async function compileCapsule() {
  const result = Bun.spawnSync(["sf", "build"], { cwd: root, stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) {
    throw new Error(
      `\`sf build\` failed while materializing the app shell:\n${result.stderr.toString()}`,
    );
  }
}

const started = Date.now();
const { articles, restBaseUrl } = await fetchArticles();
const sourceUrl = new URL(WORDPRESS_URL).origin + new URL(WORDPRESS_URL).pathname.replace(/\/$/, "");
const sourceHost = new URL(WORDPRESS_URL).host;

const documents = searchDocuments(articles);
await writeSearchIndex(documents, restBaseUrl);
console.log(`Search index: ${documents.length} documents → shared/search-index.ts`);

// Also ship the index as a plain file, so it is inspectable without the endpoint.
await writeFile(
  path.join(root, "search-index.json"),
  `${JSON.stringify(
    {
      source: restBaseUrl,
      builtAt: new Date().toISOString(),
      documents: documents.map(({ text: _text, ...rest }) => rest),
    },
    null,
    2,
  )}\n`,
);

await compileCapsule();
const importMap = await readImportMap();
console.log("App shell: import map recovered for the static pages");

await rm(path.join(root, "posts"), { recursive: true, force: true });
await mkdir(path.join(root, "posts"), { recursive: true });

await writeFile(path.join(root, "home.html"), renderIndex(articles, sourceHost, sourceUrl));
await Promise.all(
  articles.map((article) =>
    writeFile(
      path.join(root, "posts", `${article.slug}.html`),
      renderArticle(article, importMap, sourceHost, sourceUrl),
    ),
  ),
);

console.log(
  `${SITE_NAME}: home.html + ${articles.length} article pages in ${Date.now() - started}ms`,
);
console.log("Next: `sf build` to compile and stage, or `sf publish` to put it live.");
